apiVersion: v1
kind: Service
metadata:
  name: open5gs-amf-ngap-loxi
  namespace: open5gs
  annotations:
    loxilb.io/staticIP: "192.168.1.52"
    loxilb.io/lbmode: "fullnat"

spec:
  type: LoadBalancer
  loadBalancerClass: loxilb.io/loxilb

  selector:
    app.kubernetes.io/instance: open5gs
    app.kubernetes.io/name: amf

  ports:
  - name: ngap
    port: 38412
    protocol: SCTP
    targetPort: ngap
