global: {}

#################################################
# MongoDB
#################################################

mongodb:
  enabled: true
  
  image:
    registry: registry-1.docker.io
    repository: bitnami/mongodb
    digest: "sha256:681e57e88ecea84c8c23d2dd25ec0602d97b490f926662a288f888359cc2105d"

  persistence:
    enabled: true
    existingClaim: open5gs-mongodb-longhorn

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker1
#################################################
# Populate
#################################################

populate:
  enabled: false

#################################################
# Disable EPC NFs
#################################################

hss:
  enabled: false

mme:
  enabled: false

pcrf:
  enabled: false

sgwc:
  enabled: false

sgwu:
  enabled: false

sepp:
  enabled: false


#################################################
# SCP
#################################################

scp:
  enabled: true

  replicaCount: 1

  podAntiAffinityPreset: soft

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - primary
   
  services: 
    sbi: 
      sessionAffinity: ClientIP 
      sessionAffinityConfig: 
        clientIP: 
          timeoutSeconds: 10800

#################################################
# NRF
#################################################

nrf:
  enabled: true

  replicaCount: 1

  config:
    servingList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
  podAntiAffinityPreset: soft
 
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - primary

  services:
    sbi:
      sessionAffinity: ClientIP
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800


#################################################
# BSF
#################################################

bsf:
  enabled: true

  replicaCount: 1

  podAntiAffinityPreset: soft

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - primary

  services:
    sbi:
      sessionAffinity: ClientIP
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800

#################################################
# AMF
#################################################

amf:
  enabled: true

  replicaCount: 1

  podAntiAffinityPreset: soft

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - primary
  startupProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
    failureThreshold: 30

  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 3
    timeoutSeconds: 1
    failureThreshold: 2

  readinessProbe:
    enabled: true
    initialDelaySeconds: 3
    periodSeconds: 2
    timeoutSeconds: 1
    failureThreshold: 2

  config:
    guamiList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        amf_id:
          region: 2
          set: 1

    taiList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        tac:
          - 1

    plmnList:
      - plmn_id:
          mcc: "001"
          mnc: "01"
        s_nssai:
          - sst: 1
            sd: "000001"

  services:
    sbi:
      sessionAffinity: ClientIP
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800
    
    ngap:
      type: LoadBalancer
      loadBalancerClass: loxilb.io/loxilb
      loadBalancerIP: 192.168.1.51
#      externalTrafficPolicy: Cluster

#################################################
# SMF
#################################################

smf:
  enabled: true

  replicaCount: 1

  podAntiAffinityPreset: soft

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - primary

  startupProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12

  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 2

  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 3
    timeoutSeconds: 1
    failureThreshold: 2

  useDiameter: false
  useSCP: true

  config:
    logLevel: info


    session:
      - subnet: 10.45.0.1/16
        gateway: 10.45.0.1
        dnn: internet

    dns:
      - 8.8.8.8
      - 1.1.1.1


  services:
    sbi:
      sessionAffinity: ClientIP
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800

#################################################
# UPF
#################################################

upf:
  enabled: true
  
#  podAnnotations:
#    k8s.v1.cni.cncf.io/networks: |
#      [{
#        "name": "upf-macvlan",
#        "ips": ["192.168.0.251/16"]
#      }]

  replicaCount: 1

  replicaCount: 1

  podAntiAffinityPreset: soft

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - primary

  containerSecurityContext:
    enabled: true
    privileged: true
    runAsNonRoot: false
    capabilities:
      add:
        - NET_ADMIN

  command:
    - /bin/sh
    - -c
    - |
      iptables -t nat -A POSTROUTING -s 10.45.0.0/16 -j MASQUERADE
      exec open5gs-upfd -c /opt/open5gs/etc/open5gs/upf.yaml

  startupProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 12

  livenessProbe:
    enabled: true
    initialDelaySeconds: 20
    periodSeconds: 5
    timeoutSeconds: 2
    failureThreshold: 2

  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 3
    timeoutSeconds: 1
    failureThreshold: 2

  config:
    logLevel: info

    upf:
      pfcp:
        dev: eth0
        advertise: "192.168.1.52"

      gtpu:
        dev: eth0
        advertise: "192.168.1.52"

    session:
      - subnet: 10.45.0.1/16
        gateway: 10.45.0.1
        dnn: internet

    dns:
      - 8.8.8.8
      - 1.1.1.1

  services:
    gtpu:
      type: LoadBalancer
      loadBalancerClass: loxilb.io/loxilb
      loadBalancerIP: 192.168.1.52
#      externalTrafficPolicy: Cluster
#################################################
# NSSF
#################################################
nssf:
  enabled: true

  replicaCount: 1

  podAntiAffinityPreset: soft

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - primary

  config:
    nsiList:
      - uri: http://open5gs-nrf-sbi:7777
        sst: 1
        sd: "000001"

  services:
    sbi:
      sessionAffinity: ClientIP
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800

#################################################
# AUSF
#################################################

ausf:
  enabled: true

  replicaCount: 1

  podAntiAffinityPreset: soft

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - primary
  services:
    sbi:
      sessionAffinity: ClientIP
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800
#################################################
# UDM
#################################################

udm:
  enabled: true

  replicaCount: 1

  podAntiAffinityPreset: soft

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - primary
  services:
    sbi:
      sessionAffinity: ClientIP
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800

#################################################
# UDR
#################################################

udr:
  enabled: true

  replicaCount: 1

  podAntiAffinityPreset: soft

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - primary
  services:
    sbi:
      sessionAffinity: ClientIP
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800

#################################################
# PCF
#################################################

pcf:
  enabled: true

  replicaCount: 1

  podAntiAffinityPreset: soft

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - primary
  services:
    sbi:
      sessionAffinity: ClientIP
      sessionAffinityConfig:
        clientIP:
          timeoutSeconds: 10800

#################################################
# WEBUI
#################################################

webui:
  enabled: true

  replicaCount: 1

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: role
            operator: In
            values:
            - primary

  services:
    http:
      type: NodePort

      nodePorts:
        http: "30999"
